.github/workflows/pages.yml, .github/workflows/python_ci.yml, README.md, docs/data/simple_cohort/PMID_36446582_Alves_2019.json, docs/data/simple_cohort/PMID_36446582_Bianchi_2018.json, docs/data/simple_cohort/PMID_36446582_Gnazzo_2020_P1.json, docs/data/simple_cohort/PMID_36446582_KBG12.json, docs/data/simple_cohort/PMID_36446582_Kim_2015_P1.json, docs/user-guide/exploratory.rst, docs/user-guide/input-data.rst, src/genophenocorr/model/_cohort.py, src/genophenocorr/preprocessing/_config.py
Add a section for loading phenopackets, re-enable CI, add a small test cohort for the tutorial.
=> Document input data requirements

.github/workflows/pages.yml, README.md
Add release badge and clean the docs before building.
=> Put a little more lipstick on the repo

src/genophenocorr/preprocessing/_config.py
Fix bug that printed out nothing if the validation issue included no solution.
=> Fix bud in summarizing errors and warnings of the notepad.

README.md, docs/tutorial.rst, src/genophenocorr/analysis/_api.py
Report the count of samples falling into genotype/phenotype category along with the number of usable samples.
=> Contextualize the count with the cohort size in the G/P result summary

dev/README.md, dev/Statistical tests.ipynb, docs/installation.rst, src/genophenocorr/analysis/__init__.py, src/genophenocorr/analysis/_config.py, src/genophenocorr/analysis/_filter.py, src/genophenocorr/analysis/_gp_analysis.py, src/genophenocorr/analysis/_gp_impl.py, src/genophenocorr/preprocessing/_config.py
Isolate the genotype-phenotype correlation analysis code into a dedicated class to set up the stage for exploring different statistical approaches.
#126
=> Isolate G/P code

.github/workflows/notebooks.yml, .github/workflows/python_ci.yml
Update names of the GitHub action jobs.
=> Update the GitHub action names

src/genophenocorr/analysis/_gp_analysis.py, src/genophenocorr/data/_toy.py, src/genophenocorr/io.py, src/genophenocorr/model/_variant.py, src/genophenocorr/preprocessing/_phenopacket.py, src/genophenocorr/preprocessing/_vep.py, src/genophenocorr/view/_cohort.py, src/genophenocorr/view/templates/cohort.html, tests/analysis/predicate/genotype/conftest.py, tests/analysis/predicate/genotype/test_allele_counter.py, tests/analysis/test_mtc_filter.py, tests/conftest.py, tests/test_data/SUOX.json
Closes #190 
Genotype table now looks like this:
=> Expanded table of genotypes

src/genophenocorr/model/_variant.py, src/genophenocorr/view/_cohort.py
- if we add a field to a class, we must use it in dunder methods (e.g. for hashing, equality tests, and `str` and `repr`)
- we must pay attention to data types
=> Fix some bugs

src/genophenocorr/analysis/_api.py, src/genophenocorr/analysis/_gp_impl.py, tests/analysis/test_examples.py
This will close #98 
Added a property to GenotypePhenotypeAnalysisResult called total_tests and it reports the total number of phenotype tests that were run for that analysis.
=> Reporting the number of tests in GenotypePhenotypeAnalysisResult

src/genophenocorr/preprocessing/_phenopacket.py, tests/preprocessing/test_phenopacket.py
Fix bug in calculation of change length for CNVs.
Fixes #203
=> Fix bug in change length calculation for CNVs

src/genophenocorr/analysis/predicate/phenotype/_pheno.py, src/genophenocorr/data/_toy.py, src/genophenocorr/io.py, src/genophenocorr/model/_cohort.py, src/genophenocorr/model/_phenotype.py, src/genophenocorr/preprocessing/_phenotype.py, tests/analysis/conftest.py, tests/analysis/predicate/phenotype/test_predicate.py, tests/analysis/test_examples.py, tests/conftest.py, tests/model/test_cohort.py, tests/test_data/SUOX.json, tests/test_io.py, tests/view/test_formatter.py
Remove the `name` property from `Phenotype`.
Closes #222
=> Remove `name` from `Phenotype`.

docs/user-guide/stats.rst, src/gpsea/analysis/pscore/stats/__init__.py, src/gpsea/analysis/pscore/stats/_stats.py, tests/analysis/pscore/test_stats.py
=> Add T test

docs/user-guide/predicates.rst, src/gpsea/analysis/predicate/genotype/__init__.py, src/gpsea/analysis/predicate/genotype/_gt_predicates.py, src/gpsea/model/_base.py, tests/analysis/predicate/genotype/test_gt_predicates.py
Allow using  `Sex` and disease diagnosis as a genotype predicate.
Fixes #236 #237
=> Allow using `Sex` and disease diagnosis as a genotype predicate

docs/tutorial.rst, docs/user-guide/stats.rst
Fix the p values to reflect the updated MTC filter.
=> A minor doc fix

src/gpsea/preprocessing/_uniprot.py
Minor rearrangement of the Uniprot service.
=> Minor Uniprot service updates

src/gpsea/analysis/pcats/_impl.py, tests/analysis/pcats/test_hpo_term_analysis.py
Mainly, we do not explode with an exception, we just do not do any statistical tests.
=> Relax handling of the MTC filtering

docs/user-guide/predicates/allele_count_predicates.rst, docs/user-guide/predicates/genotype_predicates.rst, docs/user-guide/predicates/mode_of_inheritance_predicate.rst, src/gpsea/analysis/predicate/genotype/__init__.py, src/gpsea/analysis/predicate/genotype/_gt_predicates.py, src/gpsea/analysis/predicate/genotype/_test__gt_predicates.py, tests/analysis/predicate/genotype/test_gt_predicates.py
Allow grouping the genotype groups into larger units.
Fixes #284
=> Simplify the AR and biallelic predicates

docs/tutorial.rst, docs/user-guide/analyses/phenotype-groups.rst, docs/user-guide/analyses/report/tbx5_frameshift.csv, docs/user-guide/predicates/mode_of_inheritance_predicate.rst, src/gpsea/analysis/predicate/genotype/_test__gt_predicates.py, src/gpsea/preprocessing/_config.py, src/gpsea/view/_report.py, tests/analysis/predicate/genotype/test_gt_predicates.py
Update tests to reflect the genotype category label changes
=> Update tests to reflect the genotype category label changes

docs/user-guide/analyses/measurements.rst, src/gpsea/analysis/pscore/stats/_stats.py, tests/analysis/pscore/test_stats.py
=> The `nan` phenotype scores will be ignored

docs/tutorial.rst, docs/user-guide/analyses/measurements.rst, docs/user-guide/analyses/phenotype-scores.rst, docs/user-guide/analyses/survival.rst, docs/user-guide/predicates/allele_count_predicates.rst, src/gpsea/analysis/predicate/genotype/_gt_predicates.py, src/gpsea/analysis/predicate/genotype/_test__gt_predicates.py, tests/analysis/predicate/genotype/test_gt_predicates.py, tests/analysis/temporal/test_api.py
Ask for the genotype group labels individually instead of `names` tuple.
=> Ask for the predicate group labels individually

docs/tutorial.rst, docs/user-guide/exploratory.rst, src/gpsea/view/__init__.py, src/gpsea/view/_cohort.py, src/gpsea/view/_disease.py, tests/view/test_view.py
Use better names for `gpsea.view` classes.
=> Refactor `gpsea.view` package elements

src/gpsea/analysis/predicate/phenotype/_pheno.py
Traversing the ancestors is faster than traversing descendants, since a term  has a dozen ancestors on average, but significantly more descendants.
=> Use ancestors to implement HPO phenotype predicate

src/gpsea/analysis/mtc_filter/_impl.py, src/gpsea/analysis/predicate/genotype/_predicates.py, src/gpsea/analysis/predicate/genotype/_variant.py
Improve the docs and the doc tests.
=> Improve docs for the `VariantPredicates.region` predicate

docs/user-guide/analyses/measurements.rst, docs/user-guide/predicates/hpo_predicate.rst, src/gpsea/analysis/_base.py, src/gpsea/analysis/_partition.py, src/gpsea/analysis/pcats/_impl.py, src/gpsea/analysis/predicate/genotype/_gt_predicates.py, src/gpsea/analysis/predicate/phenotype/_pheno.py, src/gpsea/analysis/pscore/_api.py, src/gpsea/analysis/pscore/_measurement.py, src/gpsea/analysis/temporal/_api.py, src/gpsea/analysis/temporal/endpoint/_impl.py, tests/analysis/predicate/genotype/test_gt_predicates.py, tests/analysis/pscore/test_pscore_api.py, tests/analysis/temporal/test_endpoint.py
Expose more analysis components in the results.
=> Expose more analysis components

src/gpsea/model/_cohort.py, src/gpsea/model/_temporal.py, src/gpsea/preprocessing/__init__.py, src/gpsea/preprocessing/_config.py, src/gpsea/preprocessing/_phenopacket.py, src/gpsea/preprocessing/_test__phenopacket.py, tests/model/test_temporal.py, tests/preprocessing/test_phenopacket.py, tests/test_data/phenopackets/PMID_30968594_individual_1.json
Parse onsets formatted as ontology terms using the mid-point of the HPO onset interval.
Closes #349
=> Parse onsets formatted as ontology terms

docs/tutorial.rst, docs/user-guide/analyses/phenotype-groups.rst, docs/user-guide/mtc.rst, src/gpsea/analysis/pcats/__init__.py, src/gpsea/analysis/pcats/_config.py
Simplify configuration of HPO term analysis.
Closes #343
=> Simplify the HPO term analysis configuration

docs/tutorial.rst, docs/user-guide/analyses/partitioning/phenotype/hpo_predicate.rst
Small documentation updates to clarify tutorial section and fix a typo.
=> Small documentation updates

src/gpsea/model/_base.py, src/gpsea/model/_cohort.py, src/gpsea/model/_protein.py, src/gpsea/model/_test_gt.py, src/gpsea/preprocessing/_config.py, src/gpsea/preprocessing/_generic.py, src/gpsea/preprocessing/_vep.py, src/gpsea/view/_draw_variants.py, src/gpsea/view/_protein_visualizable.py, src/gpsea/view/_txp.py, tests/analysis/pscore/test_de_vries_scorer.py
=> Fix lints and typing annotations

README.md, docs/setup.rst, docs/user-guide/analyses/partitioning/genotype/variant_predicates.rst, docs/user-guide/analyses/phenotype-scores.rst, docs/user-guide/custom-components.rst, docs/user-guide/index.rst, src/gpsea/analysis/pscore/_api.py, src/gpsea/preprocessing/_config.py, src/gpsea/preprocessing/_phenopacket.py
=> Fix various bugs

docs/user-guide/analyses/partitioning/genotype/allele_count.rst, docs/user-guide/analyses/survival.rst, src/gpsea/analysis/_base.py, src/gpsea/analysis/clf/_gt_classifiers.py, src/gpsea/analysis/clf/_test__gt_classifiers.py, src/gpsea/analysis/pscore/_api.py, src/gpsea/analysis/temporal/_api.py, src/gpsea/config.py, tests/analysis/clf/test_gt_predicates.py, tests/analysis/pscore/test_pscore_api.py, tests/analysis/test_analysis_result.py
Update default colors, add violin plot.
=> Update plot colors, allow plotting violin plot

docs/tutorial.rst, docs/user-guide/analyses/mtc.rst, docs/user-guide/analyses/phenotype-classes.rst, src/gpsea/analysis/mtc_filter/__init__.py, src/gpsea/analysis/mtc_filter/_impl.py, src/gpsea/analysis/pcats/_config.py, tests/analysis/pcats/test_hpo_term_analysis.py, tests/analysis/test_mtc_filter.py
Rename `HpoMtcFilter` to `IfHpoFilter`.
=> Rename `HpoMtcFilter` to `IfHpoFilter`

docs/user-guide/analyses/mtc.rst, src/gpsea/analysis/mtc_filter/_impl.py, tests/analysis/test_mtc_filter.py
Remove the `HMF02` case as it was unreachable in most realistic scenarios.
=> Remove `HMF02`

.github/workflows/python_ci.yml, .gpsea_ci_cachedir/gene_to_tx_coordinates/HGNC:24650.json, .gpsea_ci_cachedir/gene_to_tx_coordinates/HGNC:2600.json, .gpsea_ci_cachedir/gene_to_tx_coordinates/HGNC:9965.json, docs/user-guide/input-data.rst, src/gpsea/preprocessing/__init__.py, src/gpsea/preprocessing/_caching.py, src/gpsea/preprocessing/_config.py, tests/conftest.py, tests/preprocessing/test_patient_and_cohort_creator.py, tests/preprocessing/test_phenopacket.py, tests/test_config.py
Improve caching of the REST API responses to speed up the analyses and the tests.
=> Improve caching of REST API responses
