docs/installation.rst, src/genophenocorr/analysis/predicate/_all_predicates.py, src/genophenocorr/preprocessing/__init__.py, src/genophenocorr/preprocessing/_config.py, src/genophenocorr/preprocessing/_phenopacket.py, src/genophenocorr/preprocessing/_test_variant.py, src/genophenocorr/preprocessing/_test_vep.py, src/genophenocorr/preprocessing/_test_vv.py, src/genophenocorr/preprocessing/_vep.py, src/genophenocorr/preprocessing/_vv.py, src/genophenocorr/preprocessing/test_data/CVDel_test.json, src/genophenocorr/preprocessing/test_data/CVDup_test.json, src/genophenocorr/preprocessing/test_data/deletion_test.json, src/genophenocorr/preprocessing/test_data/delinsert_test.json, src/genophenocorr/preprocessing/test_data/duplication_test.json, src/genophenocorr/preprocessing/test_data/insertion_test.json, src/genophenocorr/preprocessing/test_data/missense_hgvs_test.json, tests/conftest.py, tests/test_preprocessing.py
Fix #93 
The PR fixes a bug in change length calculation, removes trimming of the end coordinate before sending out to VEP for annotation, and prettifies the `GenomicInterpretation` JSON snippets.
Moreover, a documentation section regarding tests is added. From now on, we have 2 kinds of test, online and offline. The _online_ tests must be marked by `@pytest.mark.online` to not run them in standard CI due to spurious failures. In the long run, we should remove the online tests altogether and use mocks instead. The _offline_ tests are just the regular tests.
=> Fix change length bug

src/genophenocorr/model/_protein.py, src/genophenocorr/model/genome/_genome.py, src/genophenocorr/model/genome/_test_genome.py
Implement `distance_to`, `overlaps_with`, and `distance_to` on `Region` and `GenomicRegion`.
Fix #100
=> Add methods for simple genome arithmetics

src/genophenocorr/data/_toy.py, src/genophenocorr/model/__init__.py, src/genophenocorr/model/_cohort.py, src/genophenocorr/model/_phenotype.py, src/genophenocorr/preprocessing/_phenopacket.py, tests/conftest.py
Closes #140 
This created the class Disease and the function _add_disease. 
_add_disease takes a list of Phenopacket Disease objects and returns a list of this new Disease class objects.
=> Add Disease to Patient

tests/conftest.py
Restore the `test_data` fixture that was incorrectly deleted.
=> Restore the deleted `test_data_dir` fixture

src/genophenocorr/analysis/_config.py
Fix bug where input validation fails due to using sequential `if/else` instead of what should have been `if/elif/else`
Fixes #188
=> Fix bug in validation of terms to test in "specify terms" MTC strategy

docs/user-guide/input-data.rst, docs/user-guide/predicates.rst, src/genophenocorr/preprocessing/_config.py, src/genophenocorr/preprocessing/_patient.py
Removed the red background when running load_phenopacket_folder by taking the notebook warnings out of the stderr and putting them in stdout. I noticed everything was printing to the stderr file, and that always prints as red in jupyter-notebook. By moving the warnings out of the stderr file, only the errors will return with a red background now. 
Also discovered tqdm has a module specifically for jupyter-notebook, so I added that. I like that the progress bar is now blue/green ☺️
=> Removed the red background 

src/genophenocorr/analysis/_gp_analysis.py, src/genophenocorr/model/_variant.py, tests/analysis/conftest.py, tests/analysis/test_analysis.py
Took me a while but figured out where I think the best spot to check for the "ZeroDivisionError: float division by zero" error that Peter got with the cohort ACBD6. 
The error occurred because no patients had the variant he was running the analysis for ("12_114385521_114385521_C_T"). A division by zero error does not accurately represent what was wrong though, so I added a test to verify that there are any usable patients before running the analysis. 
This will close #201
=> Fixing "Division by 0" error

docs/user-guide/input-data.rst, src/gpsea/preprocessing/__init__.py, src/gpsea/preprocessing/_config.py
Simplify phenopacket loading functions. Now we can load a collection of `Phenopacket` objects, phenopackets from path to JSON files, and all JSON files in a directory.
=> Simplify phenopacket loading functions

docs/user-guide/predicates/mode_of_inheritance_predicate.rst, src/gpsea/analysis/predicate/genotype/_counter.py, src/gpsea/analysis/predicate/genotype/_gt_predicates.py, src/gpsea/analysis/predicate/genotype/_predicates.py, src/gpsea/analysis/predicate/genotype/_variant.py, tests/analysis/predicate/genotype/test_gt_predicates.py, tests/analysis/predicate/genotype/test_predicates.py
The MoI predicates will consider all variants to determine the genotype group by default. A `VariantPredicate` can be provided to select a subset of variants, if desired.
=> Simplify MoI predicates

src/gpsea/analysis/predicate/genotype/_predicates.py, src/gpsea/preprocessing/_uniprot.py, tests/preprocessing/data/uniprot_response/ITPR1_HUMAN.json, tests/preprocessing/test_uniprot.py
Our Uniprot service was not able to get metadata for some protein IDs, such as `NP_001365381.1` of *ITPR1* gene. 
In some cases, the REST response include only one result. If this happens, we will extract the metadata from the response even if there is not an exact match between the query protein ID and the cross-references included in the response.
=> Fix Uniprot API bug

src/gpsea/analysis/predicate/genotype/_api.py, tests/analysis/predicate/genotype/test_predicates.py
The PR fixes a bug where compound variant predicates were not hashable due to *not* inheriting `__hash__` from `LogicalVariantPredicate`.
=> Ensure the logical predicates are hashable

src/gpsea/model/_protein.py, src/gpsea/preprocessing/_api.py, tests/analysis/predicate/genotype/conftest.py, tests/preprocessing/test_protein_metadata.py
@ielis 
Could you give me quick feedback if this is OK?
The user will pass a dataframe and get a ProteinMetaData
I would additionally add the region type as an additional column.
This is useful for cases in which UniProt does not have the actual domains of interest (e.g. ITPR1) as well as for cases where the API does not work.
=> DataFrame for protein features

src/gpsea/view/_protein_viewer.py
If a protein has no features, an error returned when creating a ProteinVariantViewer. 
Fixed it by skipping if hgvs_p is None. It now prints an empty table.
=> Found bug if there are no protein features. 

.gitignore, docs/user-guide/mtc.rst, src/gpsea/analysis/mtc_filter/_impl.py, tests/analysis/test_mtc_filter.py
Validate the `SpecifyTermsMtcFilter` inputs. Test the validation.
Fixes #308
=> Sanitize `SpecifyTermsMtcFilter` input

src/gpsea/analysis/_base.py, src/gpsea/analysis/pcats/_impl.py, src/gpsea/analysis/predicate/genotype/_variant.py, src/gpsea/model/_cohort.py, src/gpsea/view/_base.py, src/gpsea/view/_cohort.py, src/gpsea/view/templates/cohort.html, tests/analysis/test_analysis_result.py, tests/view/test_view.py
Add convenience methods for getting information for generating of summaries:
* count of males or count of deceased cohort members.
* indices of the significant HPO terms
* count of items that were filtered out by phenotype MT filter
=> Add convenience methods on `Cohort` and result items

docs/user-guide/predicates/devries.rst, src/gpsea/analysis/pscore/_hpo.py
@ielis 
I updated the heuristic according to our discussion with Bert and Lex, and also updated the documentation. It should be ready to go.
=> Devries score update

src/gpsea/analysis/__init__.py, src/gpsea/analysis/_base.py, src/gpsea/analysis/predicate/phenotype/_pheno.py, src/gpsea/analysis/temporal/_api.py, src/gpsea/analysis/temporal/stats/_api.py, tests/analysis/temporal/test_statistics.py, tests/analysis/temporal/test_temporal_api.py, tests/analysis/test_analysis.py
Raise `AnalysisException` for weird datasets along with data computed so far to simplify troubleshooting.
For instance, Log rank test cannot compute a p value if survivals  are the same in all genotype subgroups. Here, an exception is raised to point out the issue and the survivals are reported.
Fixes #367 #371
=> Report analysis errors

docs/tutorial.rst, docs/user-guide/analyses/mtc.rst, docs/user-guide/analyses/phenotype-groups.rst, src/gpsea/analysis/mtc_filter/_impl.py
Improve the docs by adding a paragraph regarding alternative phenotype MT filter selection. Add cross-links between the relevant sections.
=> Improve the docs for specified terms MT filter

src/gpsea/__init__.py, src/gpsea/preprocessing/__init__.py, src/gpsea/preprocessing/_vv.py, tests/preprocessing/data/vv_response/HGNC:12799.json, tests/preprocessing/test_vv.py
Variant validator returns a weird transcript data for *WWOX*, with the CDS (695) ending beyond last exon end (641) for `NM_130791.1`.
We will ignore such transcripts when getting all transcripts for a gene.
Fixes #345
=> Ignore the inconsistent transcripts when getting transcripts for a gene from Variant Validator

src/gpsea/view/_protein_visualizer.py
The X-axis label was erroneous. Our users will know that the X axis represents amino acid residues, and nearly all of the plots you see like this do not have any label at all, so I am just removing it.
=> Removing erroneous X-axis label (# Codons)

docs/tutorial.rst, docs/user-guide/analyses/partitioning/genotype/variant_predicates.rst, docs/user-guide/analyses/phenotype-scores.rst, src/gpsea/model/_variant_effects.py, src/gpsea/preprocessing/_generic.py, tests/preprocessing/test_phenopacket.py, tests/test_data/phenopackets/PMID_30968594_individual_1.json, tests/test_data/phenopackets/README.md
Add support for functional annotation of imprecise translocations related to a gene. The translocations are predicted to lead to `transcript translocation` variant effect - a newly added member of the `gpsea.model.VariantEffect` enum.
Fixes [139](https://github.com/monarch-initiative/gpsea-cs/issues/139).
=> Support functional annotation of imprecise translocations

src/gpsea/model/_temporal.py, src/gpsea/preprocessing/_phenopacket.py
Basically, report parsing the error as an error and pass the message along.
=> Improve reporting of errors encountered during parsing temporal elements

docs/user-guide/exploratory.rst, src/gpsea/view/_protein_visualizable.py, src/gpsea/view/_viewers.py, tests/view/test_protein_visualizer.py, tests/view/test_viewers.py
We should not need `tx_id` to show protein information, protein ID should be enough.
Clean up some `gpsea.view` tests.
=> Simplify protein variant viewer, bugfixes

docs/conf.py, docs/user-guide/analyses/phenotype-scores.rst, docs/user-guide/analyses/survival.rst, pyproject.toml
doctests in survival.rst and phenotype_scores.rst are failing for me on my Macbook M1 MacOS v12.5
```
FAILED               [  2%]
docs/user-guide/analyses/survival.rst:0 ([doctest] survival.rst)
120 
121 We execute the analysis by running
122 
123 >>> result = survival_analysis.compare_genotype_vs_survival(
124 ...     cohort=cohort,
125 ...     gt_clf=gt_clf,
126 ...     endpoint=endpoint,
127 ... )
128 
129 >>> result.pval
Expected:
0.06200425830044376
Got:
0.06200425830044377
/Users/jtr4v/PythonProject/gpsea/docs/user-guide/analyses/survival.rst:129: DocTestFailure
```
This PR adds numtest as a test dependency and then uses ELLIPSIS_MARKER to allow approximate comparisons
=> Add numtest and use doctest.ELLIPSIS_MARKER to fix doctest errors when doing floating point number comparisons

docs/report/tbx5_all_variants.html, docs/report/tbx5_truncating_vs_missense.csv, docs/report/tbx5_truncating_vs_missense.mtc_report.html, docs/tutorial.rst, docs/user-guide/analyses/phenotype-classes.rst, docs/user-guide/analyses/report/tbx5_frameshift.csv, docs/user-guide/analyses/report/tbx5_frameshift.mtc_report.html, src/gpsea/analysis/mtc_filter/_impl.py, tests/analysis/test_mtc_filter.py
Disable `HMF01` - filtering by minimal proportion of observed HPO in a genotype class.
=> Disable `HMF01`

src/gpsea/view/_protein_visualizable.py, src/gpsea/view/_protein_visualizer.py, tests/view/test_protein_visualizer.py
Raise an exception if there is no variant annotated with respect to the target protein, when plotting a protein diagram.
Fixes #415
=> Check for protein annotations before plotting a diagram

docs/report/tbx5_truncating_vs_missense.mtc_report.html, docs/tutorial.rst, docs/user-guide/analyses/mtc.rst, docs/user-guide/analyses/phenotype-classes.rst, docs/user-guide/analyses/report/tbx5_frameshift.mtc_report.html, src/gpsea/__init__.py, src/gpsea/analysis/mtc_filter/_impl.py, src/gpsea/view/_viewers.py, src/gpsea/view/templates/stats.html, tests/analysis/pcats/test_hpo_term_analysis.py, tests/analysis/test_mtc_filter.py, tests/view/conftest.py
Remove `HMF01`, provide links to MTC filter rules to simplify their interpretation.
=> Remove HMF01, link out from MTC filter

docs/report/tbx5_truncating_vs_missense.mtc_report.html, docs/user-guide/analyses/report/tbx5_frameshift.mtc_report.html, src/gpsea/__init__.py, src/gpsea/analysis/mtc_filter/_impl.py, src/gpsea/view/templates/stats.html, tests/analysis/test_mtc_filter.py
Remove `/` to fix bug in MTC filter rule links. Include the base link in the template.
=> Fix bug in MTC filter rule links
